stages:
  - prepare
  - terraform-init
  - terraform-plan
  - terraform-apply

variables:
  TF_IN_AUTOMATION: "true"
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: "us-east-1"
  TF_BACKEND_BUCKET: "terraform-state-cloudsredevops"
  TF_BACKEND_KEY: "terraform.tfstate"
  TF_BACKEND_REGION: "us-east-2"
  TF_BACKEND_ENCRYPT: "true"
  TF_VAR_route53zoneid: $ROUTE53_ZONE_ID
  TF_VAR_auth_url: $AUTH_URL
  TF_VAR_cloudfront_origin_token: $CLOUDFRONT_ORIGIN_TOKEN

prepare:
  image: python:3.9-slim
  stage: prepare
  before_script:
    - apt-get update && apt-get install -y zip
  script:
    - echo "Creating Lambda deployment package..."
    - cd api
    - pip install -r requirements.txt -t .
    - zip -r ../terraform/lambda_function.zip .
    - cd ../terraform
    - ls -la
  artifacts:
    paths:
      - terraform/lambda_function.zip
    expire_in: 1 day

terraform_init:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  stage: terraform-init
  dependencies:
    - prepare
  script:
    - cd terraform
    - echo "bucket = \"${TF_BACKEND_BUCKET}\"" > backend.tfvars
    - echo "key = \"${TF_BACKEND_KEY}\"" >> backend.tfvars
    - echo "region = \"${TF_BACKEND_REGION}\"" >> backend.tfvars
    - echo "encrypt = ${TF_BACKEND_ENCRYPT}" >> backend.tfvars
    - terraform init -reconfigure -backend-config=backend.tfvars
  artifacts:
    paths:
      - terraform/.terraform
      - terraform/.terraform.lock.hcl
    expire_in: 1 hour

terraform_plan:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  stage: terraform-plan
  dependencies:
    - terraform_init
  script:
    - cd terraform
    - echo "aws_access_key = \"${AWS_ACCESS_KEY_ID}\"" > secrets-input.tfvars
    - echo "aws_secret_key = \"${AWS_SECRET_ACCESS_KEY}\"" >> secrets-input.tfvars
    - echo "route53zoneid = \"${TF_VAR_route53zoneid}\"" >> secrets-input.tfvars
    - echo "auth_url = \"${TF_VAR_auth_url}\"" >> secrets-input.tfvars
    - echo "cloudfront_origin_token = \"${TF_VAR_cloudfront_origin_token}\"" >> secrets-input.tfvars
    - terraform plan -var-file=secrets-input.tfvars || true
  artifacts:
    paths:
      - terraform/plan.out
    expire_in: 1 hour

terraform_apply:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  stage: terraform-apply
  dependencies:
    - terraform_plan
  script:
    - cd terraform
    - echo "bucket = \"${TF_BACKEND_BUCKET}\"" > backend.tfvars
    - echo "key = \"${TF_BACKEND_KEY}\"" >> backend.tfvars
    - echo "region = \"${TF_BACKEND_REGION}\"" >> backend.tfvars
    - echo "encrypt = ${TF_BACKEND_ENCRYPT}" >> backend.tfvars
    - terraform init -reconfigure -backend-config=backend.tfvars
    - echo "aws_access_key = \"${AWS_ACCESS_KEY_ID}\"" > secrets-input.tfvars
    - echo "aws_secret_key = \"${AWS_SECRET_ACCESS_KEY}\"" >> secrets-input.tfvars
    - echo "route53zoneid = \"${TF_VAR_route53zoneid}\"" >> secrets-input.tfvars
    - echo "auth_url = \"${TF_VAR_auth_url}\"" >> secrets-input.tfvars
    - echo "cloudfront_origin_token = \"${TF_VAR_cloudfront_origin_token}\"" >> secrets-input.tfvars
    - terraform apply -auto-approve -var-file=secrets-input.tfvars || true
  only:
    - main
  when: manual
